### ISSUE TITLE
New versionFormat option to detect from source and NOT auto-increment for App Publish task

### ISSUE THREAD

**Issue by vinay2099** [ServiceNow/servicenow-cicd-azure-extension#11]
The version autodetect is increasing the version by one but is there a way to directly commit the version from the repo itself ?

Due to this always the version is getting incremented so it comes like 1.0.0,1.0.2,1.0.4.

**Comment by chiarnglin** [comment]
I discussed with ING team, who will discuss internally whether they would like to submit a PR for this feature. (Please do!) 
As we discussed, I think we're adding a 5th option based on the existing 'detect' option. 
https://github.com/ServiceNow/servicenow-cicd-azure-extension/blob/22790fb3a17711d41f342fca03881f318044305d/src/lib/AppPublish.js#L83
Then go update the list of options
https://github.com/ServiceNow/servicenow-cicd-azure-extension/blob/a9eef95c179baf9e340a920c378a583387affb32/src/extension/Tasks/AppPublish/task.json#L46
I also noted in another issue that test coverage for unit tests doesn't cover other cases right now. 
https://github.com/ServiceNow/servicenow-cicd-azure-extension/issues/13
I'm not sure it would be fair to ask contributors to update tests where tests don't exist... of course from an open source contribution perspective, please help! But I don't think I'll require it. >___<

**Comment by vinay2099** [comment]
Hi chiarnglin,

I have created a new pull request as we discusssed. Kindly look at it and advise further.

Kind regards,
Vinay

**Comment by chiarnglin** [comment]
@vinay2099 Just published 1.7.0 with your addition, let me know how it goes!

**Comment by vinay2099** [comment]
Thanks chiarnglin. Will do the tests and update you
