### ISSUE TITLE
Yaml Intergration with Service Now 

### ISSUE THREAD

**Issue by shiju18** [ServiceNow/servicenow-cicd-azure-extension#56]
Is Service Now integration with yaml from environments approval gates is possible

We are using a Service Now marketplace extension to open a ticket from a release gate in an azure pipeline.
this process works perfectly if we use it from a classic UI release pipeline. If we set it up as an approval and gate from a yaml file, everytime the gate checks if the ticket was resolved it creates a new ticket instead. 

 Both Classic UI and YAML use the same task. I noticed the classic pipeline and YAML were using different versions of the task

**Comment by chiarng** [comment]
Are you looking for the ServiceNow DevOps extension instead? This one is the CI/CD Extension, it doesn't create the change mgmt tickets.
